/*
 * Copyright (c) 2018-2019, FusionAuth, All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */

'use strict';

var FusionAuthClient = function(apiKey, host) {
  this.apiKey = apiKey;
  this.host = host;
};

FusionAuthClient.constructor = FusionAuthClient;
//noinspection JSUnusedGlobalSymbols
FusionAuthClient.prototype = {

  /**
   * Takes an action on a user. The user being actioned is called the "actionee" and the user taking the action is called the
   * "actioner". Both user ids are required. You pass the actionee's user id into the method and the actioner's is put into the
   * request object.
   *
   * @param {string} actioneeUserId The actionee's user id.
   * @param {ActionRequest} request The action request that includes all of the information about the action being taken including
   *    the id of the action, any options and the duration (if applicable).
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  actionUser: function(actioneeUserId, request, callBack) {
      return this._start()
          .uri('/api/user/action')
          .urlSegment(actioneeUserId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Adds a user to an existing family. The family id must be specified.
   *
   * @param {string} familyId The id of the family.
   * @param {FamilyRequest} request The request object that contains all of the information used to determine which user to add to the family.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  addUserToFamily: function(familyId, request, callBack) {
      return this._start()
          .uri('/api/user/family')
          .urlSegment(familyId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Cancels the user action.
   *
   * @param {string} actionId The action id of the action to cancel.
   * @param {ActionRequest} request The action request that contains the information about the cancellation.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  cancelAction: function(actionId, request, callBack) {
      return this._start()
          .uri('/api/user/action')
          .urlSegment(actionId)
          .setJSONBody(request)
          .delete()
          .go(callBack);
  },

  /**
   * Changes a user's password using the change password Id. This usually occurs after an email has been sent to the user
   * and they clicked on a link to reset their password.
   *
   * @param {string} changePasswordId The change password Id used to find the user. This value is generated by FusionAuth once the change password workflow has been initiated.
   * @param {ChangePasswordRequest} request The change password request that contains all of the information used to change the password.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  changePassword: function(changePasswordId, request, callBack) {
      return this._start()
          .uri('/api/user/change-password')
          .urlSegment(changePasswordId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Changes a user's password using their identity (login id and password). Using a loginId instead of the changePasswordId
   * bypasses the email verification and allows a password to be changed directly without first calling the #forgotPassword
   * method.
   *
   * @param {ChangePasswordRequest} request The change password request that contains all of the information used to change the password.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  changePasswordByIdentity: function(request, callBack) {
      return this._start()
          .uri('/api/user/change-password')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Adds a comment to the user's account.
   *
   * @param {UserCommentRequest} request The request object that contains all of the information used to create the user comment.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  commentOnUser: function(request, callBack) {
      return this._start()
          .uri('/api/user/comment')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates an application. You can optionally specify an Id for the application, if not provided one will be generated.
   *
   * @param {?string} applicationId (Optional) The Id to use for the application. If not provided a secure random UUID will be generated.
   * @param {ApplicationRequest} request The request object that contains all of the information used to create the application.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createApplication: function(applicationId, request, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a new role for an application. You must specify the id of the application you are creating the role for.
   * You can optionally specify an Id for the role inside the ApplicationRole object itself, if not provided one will be generated.
   *
   * @param {string} applicationId The Id of the application to create the role on.
   * @param {?string} roleId (Optional) The Id of the role. If not provided a secure random UUID will be generated.
   * @param {ApplicationRequest} request The request object that contains all of the information used to create the application role.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createApplicationRole: function(applicationId, roleId, request, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .urlSegment("role")
          .urlSegment(roleId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates an audit log with the message and user name (usually an email). Audit logs should be written anytime you
   * make changes to the FusionAuth database. When using the FusionAuth App web interface, any changes are automatically
   * written to the audit log. However, if you are accessing the API, you must write the audit logs yourself.
   *
   * @param {AuditLogRequest} request The request object that contains all of the information used to create the audit log entry.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createAuditLog: function(request, callBack) {
      return this._start()
          .uri('/api/system/audit-log')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a user consent type. You can optionally specify an Id for the consent type, if not provided one will be generated.
   *
   * @param {?string} consentId (Optional) The Id for the consent. If not provided a secure random UUID will be generated.
   * @param {ConsentRequest} request The request object that contains all of the information used to create the consent.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createConsent: function(consentId, request, callBack) {
      return this._start()
          .uri('/api/consent')
          .urlSegment(consentId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates an email template. You can optionally specify an Id for the template, if not provided one will be generated.
   *
   * @param {?string} emailTemplateId (Optional) The Id for the template. If not provided a secure random UUID will be generated.
   * @param {EmailTemplateRequest} request The request object that contains all of the information used to create the email template.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createEmailTemplate: function(emailTemplateId, request, callBack) {
      return this._start()
          .uri('/api/email/template')
          .urlSegment(emailTemplateId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a family with the user id in the request as the owner and sole member of the family. You can optionally specify an id for the
   * family, if not provided one will be generated.
   *
   * @param {?string} familyId (Optional) The id for the family. If not provided a secure random UUID will be generated.
   * @param {FamilyRequest} request The request object that contains all of the information used to create the family.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createFamily: function(familyId, request, callBack) {
      return this._start()
          .uri('/api/user/family')
          .urlSegment(familyId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a group. You can optionally specify an Id for the group, if not provided one will be generated.
   *
   * @param {?string} groupId (Optional) The Id for the group. If not provided a secure random UUID will be generated.
   * @param {GroupRequest} request The request object that contains all of the information used to create the group.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createGroup: function(groupId, request, callBack) {
      return this._start()
          .uri('/api/group')
          .urlSegment(groupId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a member in a group.
   *
   * @param {MemberRequest} request The request object that contains all of the information used to create the group member(s).
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createGroupMembers: function(request, callBack) {
      return this._start()
          .uri('/api/group/member')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates an identity provider. You can optionally specify an Id for the identity provider, if not provided one will be generated.
   *
   * @param {?string} identityProviderId (Optional) The Id of the identity provider. If not provided a secure random UUID will be generated.
   * @param {IdentityProviderRequest} request The request object that contains all of the information used to create the identity provider.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createIdentityProvider: function(identityProviderId, request, callBack) {
      return this._start()
          .uri('/api/identity-provider')
          .urlSegment(identityProviderId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a Lambda. You can optionally specify an Id for the lambda, if not provided one will be generated.
   *
   * @param {?string} lambdaId (Optional) The Id for the lambda. If not provided a secure random UUID will be generated.
   * @param {LambdaRequest} request The request object that contains all of the information used to create the lambda.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createLambda: function(lambdaId, request, callBack) {
      return this._start()
          .uri('/api/lambda')
          .urlSegment(lambdaId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a tenant. You can optionally specify an Id for the tenant, if not provided one will be generated.
   *
   * @param {?string} tenantId (Optional) The Id for the tenant. If not provided a secure random UUID will be generated.
   * @param {TenantRequest} request The request object that contains all of the information used to create the tenant.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createTenant: function(tenantId, request, callBack) {
      return this._start()
          .uri('/api/tenant')
          .urlSegment(tenantId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a user. You can optionally specify an Id for the user, if not provided one will be generated.
   *
   * @param {?string} userId (Optional) The Id for the user. If not provided a secure random UUID will be generated.
   * @param {UserRequest} request The request object that contains all of the information used to create the user.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createUser: function(userId, request, callBack) {
      return this._start()
          .uri('/api/user')
          .urlSegment(userId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a user action. This action cannot be taken on a user until this call successfully returns. Anytime after
   * that the user action can be applied to any user.
   *
   * @param {?string} userActionId (Optional) The Id for the user action. If not provided a secure random UUID will be generated.
   * @param {UserActionRequest} request The request object that contains all of the information used to create the user action.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createUserAction: function(userActionId, request, callBack) {
      return this._start()
          .uri('/api/user-action')
          .urlSegment(userActionId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a user reason. This user action reason cannot be used when actioning a user until this call completes
   * successfully. Anytime after that the user action reason can be used.
   *
   * @param {?string} userActionReasonId (Optional) The Id for the user action reason. If not provided a secure random UUID will be generated.
   * @param {UserActionReasonRequest} request The request object that contains all of the information used to create the user action reason.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createUserActionReason: function(userActionReasonId, request, callBack) {
      return this._start()
          .uri('/api/user-action-reason')
          .urlSegment(userActionReasonId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a single User consent.
   *
   * @param {?string} userConsentId (Optional) The Id for the User consent. If not provided a secure random UUID will be generated.
   * @param {UserConsentRequest} request The request that contains the user consent information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createUserConsent: function(userConsentId, request, callBack) {
      return this._start()
          .uri('/api/user/consent')
          .urlSegment(userConsentId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Creates a webhook. You can optionally specify an Id for the webhook, if not provided one will be generated.
   *
   * @param {?string} webhookId (Optional) The Id for the webhook. If not provided a secure random UUID will be generated.
   * @param {WebhookRequest} request The request object that contains all of the information used to create the webhook.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  createWebhook: function(webhookId, request, callBack) {
      return this._start()
          .uri('/api/webhook')
          .urlSegment(webhookId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Deactivates the application with the given Id.
   *
   * @param {string} applicationId The Id of the application to deactivate.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deactivateApplication: function(applicationId, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .delete()
          .go(callBack);
  },

  /**
   * Deactivates the user with the given Id.
   *
   * @param {string} userId The Id of the user to deactivate.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deactivateUser: function(userId, callBack) {
      return this._start()
          .uri('/api/user')
          .urlSegment(userId)
          .delete()
          .go(callBack);
  },

  /**
   * Deactivates the user action with the given Id.
   *
   * @param {string} userActionId The Id of the user action to deactivate.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deactivateUserAction: function(userActionId, callBack) {
      return this._start()
          .uri('/api/user-action')
          .urlSegment(userActionId)
          .delete()
          .go(callBack);
  },

  /**
   * Deactivates the users with the given ids.
   *
   * @param {Array<string>} userIds The ids of the users to deactivate.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deactivateUsers: function(userIds, callBack) {
      return this._start()
          .uri('/api/user/bulk')
          .urlParameter('userId', userIds)
          .delete()
          .go(callBack);
  },

  /**
   * Hard deletes an application. This is a dangerous operation and should not be used in most circumstances. This will
   * delete the application, any registrations for that application, metrics and reports for the application, all the
   * roles for the application, and any other data associated with the application. This operation could take a very
   * long time, depending on the amount of data in your database.
   *
   * @param {string} applicationId The Id of the application to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteApplication: function(applicationId, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .urlParameter('hardDelete', true)
          .delete()
          .go(callBack);
  },

  /**
   * Hard deletes an application role. This is a dangerous operation and should not be used in most circumstances. This
   * permanently removes the given role from all users that had it.
   *
   * @param {string} applicationId The Id of the application to deactivate.
   * @param {string} roleId The Id of the role to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteApplicationRole: function(applicationId, roleId, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .urlSegment("role")
          .urlSegment(roleId)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the consent for the given Id.
   *
   * @param {string} consentId The Id of the consent to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteConsent: function(consentId, callBack) {
      return this._start()
          .uri('/api/consent')
          .urlSegment(consentId)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the email template for the given Id.
   *
   * @param {string} emailTemplateId The Id of the email template to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteEmailTemplate: function(emailTemplateId, callBack) {
      return this._start()
          .uri('/api/email/template')
          .urlSegment(emailTemplateId)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the group for the given Id.
   *
   * @param {string} groupId The Id of the group to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteGroup: function(groupId, callBack) {
      return this._start()
          .uri('/api/group')
          .urlSegment(groupId)
          .delete()
          .go(callBack);
  },

  /**
   * Removes users as members of a group.
   *
   * @param {MemberDeleteRequest} request The member request that contains all of the information used to remove members to the group.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteGroupMembers: function(request, callBack) {
      return this._start()
          .uri('/api/group/member')
          .setJSONBody(request)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the identity provider for the given Id.
   *
   * @param {string} identityProviderId The Id of the identity provider to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteIdentityProvider: function(identityProviderId, callBack) {
      return this._start()
          .uri('/api/identity-provider')
          .urlSegment(identityProviderId)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the key for the given Id.
   *
   * @param {string} keyOd The Id of the key to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteKey: function(keyOd, callBack) {
      return this._start()
          .uri('/api/key')
          .urlSegment(keyOd)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the lambda for the given Id.
   *
   * @param {string} lambdaId The Id of the lambda to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteLambda: function(lambdaId, callBack) {
      return this._start()
          .uri('/api/lambda')
          .urlSegment(lambdaId)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the user registration for the given user and application.
   *
   * @param {string} userId The Id of the user whose registration is being deleted.
   * @param {string} applicationId The Id of the application to remove the registration for.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteRegistration: function(userId, applicationId, callBack) {
      return this._start()
          .uri('/api/user/registration')
          .urlSegment(userId)
          .urlSegment(applicationId)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the tenant for the given Id.
   *
   * @param {string} tenantId The Id of the tenant to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteTenant: function(tenantId, callBack) {
      return this._start()
          .uri('/api/tenant')
          .urlSegment(tenantId)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the user for the given Id. This permanently deletes all information, metrics, reports and data associated
   * with the user.
   *
   * @param {string} userId The Id of the user to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteUser: function(userId, callBack) {
      return this._start()
          .uri('/api/user')
          .urlSegment(userId)
          .urlParameter('hardDelete', true)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the user action for the given Id. This permanently deletes the user action and also any history and logs of
   * the action being applied to any users.
   *
   * @param {string} userActionId The Id of the user action to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteUserAction: function(userActionId, callBack) {
      return this._start()
          .uri('/api/user-action')
          .urlSegment(userActionId)
          .urlParameter('hardDelete', true)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the user action reason for the given Id.
   *
   * @param {string} userActionReasonId The Id of the user action reason to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteUserActionReason: function(userActionReasonId, callBack) {
      return this._start()
          .uri('/api/user-action-reason')
          .urlSegment(userActionReasonId)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the users with the given ids.
   *
   * @param {UserDeleteRequest} request The ids of the users to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteUsers: function(request, callBack) {
      return this._start()
          .uri('/api/user/bulk')
          .setJSONBody(request)
          .delete()
          .go(callBack);
  },

  /**
   * Deletes the webhook for the given Id.
   *
   * @param {string} webhookId The Id of the webhook to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  deleteWebhook: function(webhookId, callBack) {
      return this._start()
          .uri('/api/webhook')
          .urlSegment(webhookId)
          .delete()
          .go(callBack);
  },

  /**
   * Disable Two Factor authentication for a user.
   *
   * @param {string} userId The Id of the User for which you're disabling Two Factor authentication.
   * @param {string} code The Two Factor code used verify the the caller knows the Two Factor secret.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  disableTwoFactor: function(userId, code, callBack) {
      return this._start()
          .uri('/api/user/two-factor')
          .urlParameter('userId', userId)
          .urlParameter('code', code)
          .delete()
          .go(callBack);
  },

  /**
   * Enable Two Factor authentication for a user.
   *
   * @param {string} userId The Id of the user to enable Two Factor authentication.
   * @param {TwoFactorRequest} request The two factor enable request information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  enableTwoFactor: function(userId, request, callBack) {
      return this._start()
          .uri('/api/user/two-factor')
          .urlSegment(userId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Exchange a refresh token for a new JWT.
   *
   * @param {RefreshRequest} request The refresh request.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  exchangeRefreshTokenForJWT: function(request, callBack) {
      return this._start()
          .uri('/api/jwt/refresh')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Begins the forgot password sequence, which kicks off an email to the user so that they can reset their password.
   *
   * @param {ForgotPasswordRequest} request The request that contains the information about the user so that they can be emailed.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  forgotPassword: function(request, callBack) {
      return this._start()
          .uri('/api/user/forgot-password')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Generate a new Email Verification Id to be used with the Verify Email API. This API will not attempt to send an
   * email to the User. This API may be used to collect the verificationId for use with a third party system.
   *
   * @param {string} email The email address of the user that needs a new verification email.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  generateEmailVerificationId: function(email, callBack) {
      return this._start()
          .uri('/api/user/verify-email')
          .urlParameter('email', email)
          .urlParameter('sendVerifyPasswordEmail', false)
          .put()
          .go(callBack);
  },

  /**
   * Generate a new RSA or EC key pair or an HMAC secret.
   *
   * @param {?string} keyId (Optional) The Id for the key. If not provided a secure random UUID will be generated.
   * @param {KeyRequest} request The request object that contains all of the information used to create the key.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  generateKey: function(keyId, request, callBack) {
      return this._start()
          .uri('/api/key/generate')
          .urlSegment(keyId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Generate a new Application Registration Verification Id to be used with the Verify Registration API. This API will not attempt to send an
   * email to the User. This API may be used to collect the verificationId for use with a third party system.
   *
   * @param {string} email The email address of the user that needs a new verification email.
   * @param {string} applicationId The Id of the application to be verified.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  generateRegistrationVerificationId: function(email, applicationId, callBack) {
      return this._start()
          .uri('/api/user/verify-registration')
          .urlParameter('email', email)
          .urlParameter('sendVerifyPasswordEmail', false)
          .urlParameter('applicationId', applicationId)
          .put()
          .go(callBack);
  },

  /**
   * Generate a Two Factor secret that can be used to enable Two Factor authentication for a User. The response will contain
   * both the secret and a Base32 encoded form of the secret which can be shown to a User when using a 2 Step Authentication
   * application such as Google Authenticator.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  generateTwoFactorSecret: function(callBack) {
      return this._start()
          .uri('/api/two-factor/secret')
          .get()
          .go(callBack);
  },

  /**
   * Generate a Two Factor secret that can be used to enable Two Factor authentication for a User. The response will contain
   * both the secret and a Base32 encoded form of the secret which can be shown to a User when using a 2 Step Authentication
   * application such as Google Authenticator.
   *
   * @param {string} encodedJWT The encoded JWT (access token).
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  generateTwoFactorSecretUsingJWT: function(encodedJWT, callBack) {
      return this._start()
          .uri('/api/two-factor/secret')
          .authorization('JWT ' + encodedJWT)
          .get()
          .go(callBack);
  },

  /**
   * Handles login via third-parties including Social login, external OAuth and OpenID Connect, and other
   * login systems.
   *
   * @param {IdentityProviderLoginRequest} request The third-party login request that contains information from the third-party login
   *    providers that FusionAuth uses to reconcile the user's account.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  identityProviderLogin: function(request, callBack) {
      return this._start()
          .uri('/api/identity-provider/login')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Import an existing RSA or EC key pair or an HMAC secret.
   *
   * @param {?string} keyId (Optional) The Id for the key. If not provided a secure random UUID will be generated.
   * @param {KeyRequest} request The request object that contains all of the information used to create the key.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  importKey: function(keyId, request, callBack) {
      return this._start()
          .uri('/api/key/import')
          .urlSegment(keyId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Bulk imports multiple users. This does some validation, but then tries to run batch inserts of users. This reduces
   * latency when inserting lots of users. Therefore, the error response might contain some information about failures,
   * but it will likely be pretty generic.
   *
   * @param {ImportRequest} request The request that contains all of the information about all of the users to import.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  importUsers: function(request, callBack) {
      return this._start()
          .uri('/api/user/import')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Issue a new access token (JWT) for the requested Application after ensuring the provided JWT is valid. A valid
   * access token is properly signed and not expired.
   * <p>
   * This API may be used in an SSO configuration to issue new tokens for another application after the user has
   * obtained a valid token from authentication.
   *
   * @param {string} applicationId The Application Id for which you are requesting a new access token be issued.
   * @param {string} encodedJWT The encoded JWT (access token).
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  issueJWT: function(applicationId, encodedJWT, callBack) {
      return this._start()
          .uri('/api/jwt/issue')
          .authorization('JWT ' + encodedJWT)
          .urlParameter('applicationId', applicationId)
          .get()
          .go(callBack);
  },

  /**
   * Logs a user in.
   *
   * @param {LoginRequest} request The login request that contains the user credentials used to log them in.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  login: function(request, callBack) {
      return this._start()
          .uri('/api/login')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Sends a ping to FusionAuth indicating that the user was automatically logged into an application. When using
   * FusionAuth's SSO or your own, you should call this if the user is already logged in centrally, but accesses an
   * application where they no longer have a session. This helps correctly track login counts, times and helps with
   * reporting.
   *
   * @param {string} userId The Id of the user that was logged in.
   * @param {string} applicationId The Id of the application that they logged into.
   * @param {?string} callerIPAddress (Optional) The IP address of the end-user that is logging in. If a null value is provided
   *    the IP address will be that of the client or last proxy that sent the request.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  loginPing: function(userId, applicationId, callerIPAddress, callBack) {
      return this._start()
          .uri('/api/login')
          .urlSegment(userId)
          .urlSegment(applicationId)
          .urlParameter('ipAddress', callerIPAddress)
          .put()
          .go(callBack);
  },

  /**
   * The Logout API is intended to be used to remove the refresh token and access token cookies if they exist on the
   * client and revoke the refresh token stored. This API does nothing if the request does not contain an access
   * token or refresh token cookies.
   *
   * @param {boolean} global When this value is set to true all of the refresh tokens issued to the owner of the
   *    provided token will be revoked.
   * @param {?string} refreshToken (Optional) The refresh_token as a request parameter instead of coming in via a cookie.
   *    If provided this takes precedence over the cookie.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  logout: function(global, refreshToken, callBack) {
      return this._start()
          .header('Content-Type', 'text/plain')
          .uri('/api/logout')
          .urlParameter('global', global)
          .urlParameter('refreshToken', refreshToken)
          .post()
          .go(callBack);
  },

  /**
   * Retrieves the identity provider for the given domain. A 200 response code indicates the domain is managed
   * by a registered identity provider. A 404 indicates the domain is not managed.
   *
   * @param {string} domain The domain or email address to lookup.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  lookupIdentityProvider: function(domain, callBack) {
      return this._start()
          .uri('/api/identity-provider/lookup')
          .urlParameter('domain', domain)
          .get()
          .go(callBack);
  },

  /**
   * Modifies a temporal user action by changing the expiration of the action and optionally adding a comment to the
   * action.
   *
   * @param {string} actionId The Id of the action to modify. This is technically the user action log id.
   * @param {ActionRequest} request The request that contains all of the information about the modification.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  modifyAction: function(actionId, request, callBack) {
      return this._start()
          .uri('/api/user/action')
          .urlSegment(actionId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Complete a login request using a passwordless code
   *
   * @param {PasswordlessLoginRequest} request The passwordless login request that contains all of the information used to complete login.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  passwordlessLogin: function(request, callBack) {
      return this._start()
          .uri('/api/passwordless/login')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Reactivates the application with the given Id.
   *
   * @param {string} applicationId The Id of the application to reactivate.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  reactivateApplication: function(applicationId, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .urlParameter('reactivate', true)
          .put()
          .go(callBack);
  },

  /**
   * Reactivates the user with the given Id.
   *
   * @param {string} userId The Id of the user to reactivate.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  reactivateUser: function(userId, callBack) {
      return this._start()
          .uri('/api/user')
          .urlSegment(userId)
          .urlParameter('reactivate', true)
          .put()
          .go(callBack);
  },

  /**
   * Reactivates the user action with the given Id.
   *
   * @param {string} userActionId The Id of the user action to reactivate.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  reactivateUserAction: function(userActionId, callBack) {
      return this._start()
          .uri('/api/user-action')
          .urlSegment(userActionId)
          .urlParameter('reactivate', true)
          .put()
          .go(callBack);
  },

  /**
   * Reconcile a User to FusionAuth using JWT issued from another Identity Provider.
   *
   * @param {IdentityProviderLoginRequest} request The reconcile request that contains the data to reconcile the User.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  reconcileJWT: function(request, callBack) {
      return this._start()
          .uri('/api/jwt/reconcile')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Registers a user for an application. If you provide the User and the UserRegistration object on this request, it
   * will create the user as well as register them for the application. This is called a Full Registration. However, if
   * you only provide the UserRegistration object, then the user must already exist and they will be registered for the
   * application. The user id can also be provided and it will either be used to look up an existing user or it will be
   * used for the newly created User.
   *
   * @param {?string} userId (Optional) The Id of the user being registered for the application and optionally created.
   * @param {RegistrationRequest} request The request that optionally contains the User and must contain the UserRegistration.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  register: function(userId, request, callBack) {
      return this._start()
          .uri('/api/user/registration')
          .urlSegment(userId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Removes a user from the family with the given id.
   *
   * @param {string} familyId The id of the family to remove the user from.
   * @param {string} userId The id of the user to remove from the family.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  removeUserFromFamily: function(familyId, userId, callBack) {
      return this._start()
          .uri('/api/user/family')
          .urlSegment(familyId)
          .urlSegment(userId)
          .delete()
          .go(callBack);
  },

  /**
   * Re-sends the verification email to the user.
   *
   * @param {string} email The email address of the user that needs a new verification email.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  resendEmailVerification: function(email, callBack) {
      return this._start()
          .uri('/api/user/verify-email')
          .urlParameter('email', email)
          .put()
          .go(callBack);
  },

  /**
   * Re-sends the application registration verification email to the user.
   *
   * @param {string} email The email address of the user that needs a new verification email.
   * @param {string} applicationId The Id of the application to be verified.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  resendRegistrationVerification: function(email, applicationId, callBack) {
      return this._start()
          .uri('/api/user/verify-registration')
          .urlParameter('email', email)
          .urlParameter('applicationId', applicationId)
          .put()
          .go(callBack);
  },

  /**
   * Retrieves a single action log (the log of a user action that was taken on a user previously) for the given Id.
   *
   * @param {string} actionId The Id of the action to retrieve.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveAction: function(actionId, callBack) {
      return this._start()
          .uri('/api/user/action')
          .urlSegment(actionId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the actions for the user with the given Id. This will return all time based actions that are active,
   * and inactive as well as non-time based actions.
   *
   * @param {string} userId The Id of the user to fetch the actions for.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveActions: function(userId, callBack) {
      return this._start()
          .uri('/api/user/action')
          .urlParameter('userId', userId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the actions for the user with the given Id that are currently preventing the User from logging in.
   *
   * @param {string} userId The Id of the user to fetch the actions for.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveActionsPreventingLogin: function(userId, callBack) {
      return this._start()
          .uri('/api/user/action')
          .urlParameter('userId', userId)
          .urlParameter('preventingLogin', true)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the actions for the user with the given Id that are currently active.
   * An active action means one that is time based and has not been canceled, and has not ended.
   *
   * @param {string} userId The Id of the user to fetch the actions for.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveActiveActions: function(userId, callBack) {
      return this._start()
          .uri('/api/user/action')
          .urlParameter('userId', userId)
          .urlParameter('active', true)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the application for the given id or all of the applications if the id is null.
   *
   * @param {?string} applicationId (Optional) The application id.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveApplication: function(applicationId, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the applications.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveApplications: function(callBack) {
      return this._start()
          .uri('/api/application')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves a single audit log for the given Id.
   *
   * @param {number} auditLogId The Id of the audit log to retrieve.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveAuditLog: function(auditLogId, callBack) {
      return this._start()
          .uri('/api/system/audit-log')
          .urlSegment(auditLogId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the Consent for the given Id.
   *
   * @param {string} consentId The Id of the consent.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveConsent: function(consentId, callBack) {
      return this._start()
          .uri('/api/consent')
          .urlSegment(consentId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the consent.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveConsents: function(callBack) {
      return this._start()
          .uri('/api/consent')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the daily active user report between the two instants. If you specify an application id, it will only
   * return the daily active counts for that application.
   *
   * @param {?string} applicationId (Optional) The application id.
   * @param {number} start The start instant as UTC milliseconds since Epoch.
   * @param {number} end The end instant as UTC milliseconds since Epoch.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveDailyActiveReport: function(applicationId, start, end, callBack) {
      return this._start()
          .uri('/api/report/daily-active-user')
          .urlParameter('applicationId', applicationId)
          .urlParameter('start', start)
          .urlParameter('end', end)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the email template for the given Id. If you don't specify the id, this will return all of the email templates.
   *
   * @param {?string} emailTemplateId (Optional) The Id of the email template.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveEmailTemplate: function(emailTemplateId, callBack) {
      return this._start()
          .uri('/api/email/template')
          .urlSegment(emailTemplateId)
          .get()
          .go(callBack);
  },

  /**
   * Creates a preview of the email template provided in the request. This allows you to preview an email template that
   * hasn't been saved to the database yet. The entire email template does not need to be provided on the request. This
   * will create the preview based on whatever is given.
   *
   * @param {PreviewRequest} request The request that contains the email template and optionally a locale to render it in.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveEmailTemplatePreview: function(request, callBack) {
      return this._start()
          .uri('/api/email/template/preview')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Retrieves all of the email templates.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveEmailTemplates: function(callBack) {
      return this._start()
          .uri('/api/email/template')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves a single event log for the given Id.
   *
   * @param {number} eventLogId The Id of the event log to retrieve.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveEventLog: function(eventLogId, callBack) {
      return this._start()
          .uri('/api/system/event-log')
          .urlSegment(eventLogId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the families that a user belongs to.
   *
   * @param {string} userId The User's id
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveFamilies: function(userId, callBack) {
      return this._start()
          .uri('/api/user/family')
          .urlParameter('userId', userId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the members of a family by the unique Family Id.
   *
   * @param {string} familyId The unique Id of the Family.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveFamilyMembersByFamilyId: function(familyId, callBack) {
      return this._start()
          .uri('/api/user/family')
          .urlSegment(familyId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the group for the given Id.
   *
   * @param {string} groupId The Id of the group.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveGroup: function(groupId, callBack) {
      return this._start()
          .uri('/api/group')
          .urlSegment(groupId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the groups.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveGroups: function(callBack) {
      return this._start()
          .uri('/api/group')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the identity provider for the given id or all of the identity providers if the id is null.
   *
   * @param {?string} identityProviderId (Optional) The identity provider id.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveIdentityProvider: function(identityProviderId, callBack) {
      return this._start()
          .uri('/api/identity-provider')
          .urlSegment(identityProviderId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the identity providers.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveIdentityProviders: function(callBack) {
      return this._start()
          .uri('/api/identity-provider')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the actions for the user with the given Id that are currently inactive.
   * An inactive action means one that is time based and has been canceled or has expired, or is not time based.
   *
   * @param {string} userId The Id of the user to fetch the actions for.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveInactiveActions: function(userId, callBack) {
      return this._start()
          .uri('/api/user/action')
          .urlParameter('userId', userId)
          .urlParameter('active', false)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the applications that are currently inactive.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveInactiveApplications: function(callBack) {
      return this._start()
          .uri('/api/application')
          .urlParameter('inactive', true)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the user actions that are currently inactive.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveInactiveUserActions: function(callBack) {
      return this._start()
          .uri('/api/user-action')
          .urlParameter('inactive', true)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the available integrations.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveIntegration: function(callBack) {
      return this._start()
          .uri('/api/integration')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the Public Key configured for verifying JSON Web Tokens (JWT) by the key Id. If the key Id is provided a
   * single public key will be returned if one is found by that id. If the optional parameter key Id is not provided all
   * public keys will be returned.
   *
   * @param {?string} keyId (Optional) The Id of the public key.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveJWTPublicKey: function(keyId, callBack) {
      return this._start()
          .uri('/api/jwt/public-key')
          .urlSegment(keyId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all Public Keys configured for verifying JSON Web Tokens (JWT).
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveJWTPublicKeys: function(callBack) {
      return this._start()
          .uri('/api/jwt/public-key')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the key for the given Id.
   *
   * @param {string} keyId The Id of the key.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveKey: function(keyId, callBack) {
      return this._start()
          .uri('/api/key')
          .urlSegment(keyId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the keys.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveKeys: function(callBack) {
      return this._start()
          .uri('/api/key')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the lambda for the given Id.
   *
   * @param {string} lambdaId The Id of the lambda.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveLambda: function(lambdaId, callBack) {
      return this._start()
          .uri('/api/lambda')
          .urlSegment(lambdaId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the lambdas.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveLambdas: function(callBack) {
      return this._start()
          .uri('/api/lambda')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the lambdas for the provided type.
   *
   * @param {LambdaType} type The type of the lambda to return.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveLambdasByType: function(type, callBack) {
      return this._start()
          .uri('/api/lambda')
          .urlParameter('type', type)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the login report between the two instants. If you specify an application id, it will only return the
   * login counts for that application.
   *
   * @param {?string} applicationId (Optional) The application id.
   * @param {number} start The start instant as UTC milliseconds since Epoch.
   * @param {number} end The end instant as UTC milliseconds since Epoch.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveLoginReport: function(applicationId, start, end, callBack) {
      return this._start()
          .uri('/api/report/login')
          .urlParameter('applicationId', applicationId)
          .urlParameter('start', start)
          .urlParameter('end', end)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the monthly active user report between the two instants. If you specify an application id, it will only
   * return the monthly active counts for that application.
   *
   * @param {?string} applicationId (Optional) The application id.
   * @param {number} start The start instant as UTC milliseconds since Epoch.
   * @param {number} end The end instant as UTC milliseconds since Epoch.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveMonthlyActiveReport: function(applicationId, start, end, callBack) {
      return this._start()
          .uri('/api/report/monthly-active-user')
          .urlParameter('applicationId', applicationId)
          .urlParameter('start', start)
          .urlParameter('end', end)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the Oauth2 configuration for the application for the given Application Id.
   *
   * @param {string} applicationId The Id of the Application to retrieve OAuth configuration.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveOauthConfiguration: function(applicationId, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .urlSegment("oauth-configuration")
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the password validation rules.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrievePasswordValidationRules: function(callBack) {
      return this._start()
          .uri('/api/system-configuration/password-validation-rules')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the children for the given parent email address.
   *
   * @param {string} parentEmail The email of the parent.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrievePendingChildren: function(parentEmail, callBack) {
      return this._start()
          .uri('/api/user/family/pending')
          .urlParameter('parentEmail', parentEmail)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the last number of login records.
   *
   * @param {number} offset The initial record. e.g. 0 is the last login, 100 will be the 100th most recent login.
   * @param {number} limit (Optional, defaults to 10) The number of records to retrieve.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveRecentLogins: function(offset, limit, callBack) {
      return this._start()
          .uri('/api/user/recent-login')
          .urlParameter('offset', offset)
          .urlParameter('limit', limit)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the refresh tokens that belong to the user with the given Id.
   *
   * @param {string} userId The Id of the user.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveRefreshTokens: function(userId, callBack) {
      return this._start()
          .uri('/api/jwt/refresh')
          .urlParameter('userId', userId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user registration for the user with the given id and the given application id.
   *
   * @param {string} userId The Id of the user.
   * @param {string} applicationId The Id of the application.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveRegistration: function(userId, applicationId, callBack) {
      return this._start()
          .uri('/api/user/registration')
          .urlSegment(userId)
          .urlSegment(applicationId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the registration report between the two instants. If you specify an application id, it will only return
   * the registration counts for that application.
   *
   * @param {?string} applicationId (Optional) The application id.
   * @param {number} start The start instant as UTC milliseconds since Epoch.
   * @param {number} end The end instant as UTC milliseconds since Epoch.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveRegistrationReport: function(applicationId, start, end, callBack) {
      return this._start()
          .uri('/api/report/registration')
          .urlParameter('applicationId', applicationId)
          .urlParameter('start', start)
          .urlParameter('end', end)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the system configuration.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveSystemConfiguration: function(callBack) {
      return this._start()
          .uri('/api/system-configuration')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the tenant for the given Id.
   *
   * @param {string} tenantId The Id of the tenant.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveTenant: function(tenantId, callBack) {
      return this._start()
          .uri('/api/tenant')
          .urlSegment(tenantId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the tenants.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveTenants: function(callBack) {
      return this._start()
          .uri('/api/tenant')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the totals report. This contains all of the total counts for each application and the global registration
   * count.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveTotalReport: function(callBack) {
      return this._start()
          .uri('/api/report/totals')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user for the given Id.
   *
   * @param {string} userId The Id of the user.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUser: function(userId, callBack) {
      return this._start()
          .uri('/api/user')
          .urlSegment(userId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user action for the given Id. If you pass in null for the id, this will return all of the user
   * actions.
   *
   * @param {?string} userActionId (Optional) The Id of the user action.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserAction: function(userActionId, callBack) {
      return this._start()
          .uri('/api/user-action')
          .urlSegment(userActionId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user action reason for the given Id. If you pass in null for the id, this will return all of the user
   * action reasons.
   *
   * @param {?string} userActionReasonId (Optional) The Id of the user action reason.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserActionReason: function(userActionReasonId, callBack) {
      return this._start()
          .uri('/api/user-action-reason')
          .urlSegment(userActionReasonId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all the user action reasons.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserActionReasons: function(callBack) {
      return this._start()
          .uri('/api/user-action-reason')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the user actions.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserActions: function(callBack) {
      return this._start()
          .uri('/api/user-action')
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user by a change password Id. The intended use of this API is to retrieve a user after the forgot
   * password workflow has been initiated and you may not know the user's email or username.
   *
   * @param {string} changePasswordId The unique change password Id that was sent via email or returned by the Forgot Password API.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserByChangePasswordId: function(changePasswordId, callBack) {
      return this._start()
          .uri('/api/user')
          .urlParameter('changePasswordId', changePasswordId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user for the given email.
   *
   * @param {string} email The email of the user.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserByEmail: function(email, callBack) {
      return this._start()
          .uri('/api/user')
          .urlParameter('email', email)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user for the loginId. The loginId can be either the username or the email.
   *
   * @param {string} loginId The email or username of the user.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserByLoginId: function(loginId, callBack) {
      return this._start()
          .uri('/api/user')
          .urlParameter('loginId', loginId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user for the given username.
   *
   * @param {string} username The username of the user.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserByUsername: function(username, callBack) {
      return this._start()
          .uri('/api/user')
          .urlParameter('username', username)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user by a verificationId. The intended use of this API is to retrieve a user after the forgot
   * password workflow has been initiated and you may not know the user's email or username.
   *
   * @param {string} verificationId The unique verification Id that has been set on the user object.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserByVerificationId: function(verificationId, callBack) {
      return this._start()
          .uri('/api/user')
          .urlParameter('verificationId', verificationId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the comments for the user with the given Id.
   *
   * @param {string} userId The Id of the user.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserComments: function(userId, callBack) {
      return this._start()
          .uri('/api/user/comment')
          .urlSegment(userId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieve a single User consent by Id.
   *
   * @param {string} userConsentId The User consent Id
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserConsent: function(userConsentId, callBack) {
      return this._start()
          .uri('/api/user/consent')
          .urlSegment(userConsentId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all of the consents for a User.
   *
   * @param {string} userId The User's Id
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserConsents: function(userId, callBack) {
      return this._start()
          .uri('/api/user/consent')
          .urlParameter('userId', userId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the login report between the two instants for a particular user by Id. If you specify an application id, it will only return the
   * login counts for that application.
   *
   * @param {?string} applicationId (Optional) The application id.
   * @param {string} userId The userId id.
   * @param {number} start The start instant as UTC milliseconds since Epoch.
   * @param {number} end The end instant as UTC milliseconds since Epoch.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserLoginReport: function(applicationId, userId, start, end, callBack) {
      return this._start()
          .uri('/api/report/login')
          .urlParameter('applicationId', applicationId)
          .urlParameter('userId', userId)
          .urlParameter('start', start)
          .urlParameter('end', end)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the login report between the two instants for a particular user by login Id. If you specify an application id, it will only return the
   * login counts for that application.
   *
   * @param {?string} applicationId (Optional) The application id.
   * @param {string} loginId The userId id.
   * @param {number} start The start instant as UTC milliseconds since Epoch.
   * @param {number} end The end instant as UTC milliseconds since Epoch.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserLoginReportByLoginId: function(applicationId, loginId, start, end, callBack) {
      return this._start()
          .uri('/api/report/login')
          .urlParameter('applicationId', applicationId)
          .urlParameter('loginId', loginId)
          .urlParameter('start', start)
          .urlParameter('end', end)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the last number of login records for a user.
   *
   * @param {string} userId The Id of the user.
   * @param {number} offset The initial record. e.g. 0 is the last login, 100 will be the 100th most recent login.
   * @param {number} limit (Optional, defaults to 10) The number of records to retrieve.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserRecentLogins: function(userId, offset, limit, callBack) {
      return this._start()
          .uri('/api/user/recent-login')
          .urlParameter('userId', userId)
          .urlParameter('offset', offset)
          .urlParameter('limit', limit)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the user for the given Id. This method does not use an API key, instead it uses a JSON Web Token (JWT) for authentication.
   *
   * @param {string} encodedJWT The encoded JWT (access token).
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveUserUsingJWT: function(encodedJWT, callBack) {
      return this._start()
          .uri('/api/user')
          .authorization('JWT ' + encodedJWT)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the webhook for the given Id. If you pass in null for the id, this will return all the webhooks.
   *
   * @param {?string} webhookId (Optional) The Id of the webhook.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveWebhook: function(webhookId, callBack) {
      return this._start()
          .uri('/api/webhook')
          .urlSegment(webhookId)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves all the webhooks.
   *
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  retrieveWebhooks: function(callBack) {
      return this._start()
          .uri('/api/webhook')
          .get()
          .go(callBack);
  },

  /**
   * Revokes a single refresh token, all tokens for a user or all tokens for an application. If you provide a user id
   * and an application id, this will delete all the refresh tokens for that user for that application.
   *
   * @param {?string} token (Optional) The refresh token to delete.
   * @param {?string} userId (Optional) The user id whose tokens to delete.
   * @param {?string} applicationId (Optional) The application id of the tokens to delete.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  revokeRefreshToken: function(token, userId, applicationId, callBack) {
      return this._start()
          .uri('/api/jwt/refresh')
          .urlParameter('token', token)
          .urlParameter('userId', userId)
          .urlParameter('applicationId', applicationId)
          .delete()
          .go(callBack);
  },

  /**
   * Revokes a single User consent by Id.
   *
   * @param {string} userConsentId The User Consent Id
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  revokeUserConsent: function(userConsentId, callBack) {
      return this._start()
          .uri('/api/user/consent')
          .urlSegment(userConsentId)
          .delete()
          .go(callBack);
  },

  /**
   * Searches the audit logs with the specified criteria and pagination.
   *
   * @param {AuditLogSearchRequest} request The search criteria and pagination information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  searchAuditLogs: function(request, callBack) {
      return this._start()
          .uri('/api/system/audit-log/search')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Searches the event logs with the specified criteria and pagination.
   *
   * @param {EventLogSearchRequest} request The search criteria and pagination information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  searchEventLogs: function(request, callBack) {
      return this._start()
          .uri('/api/system/event-log/search')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Searches the login records with the specified criteria and pagination.
   *
   * @param {LoginRecordSearchRequest} request The search criteria and pagination information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  searchLoginRecords: function(request, callBack) {
      return this._start()
          .uri('/api/system/login-record/search')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Retrieves the users for the given ids. If any id is invalid, it is ignored.
   *
   * @param {Array<string>} ids The user ids to search for.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  searchUsers: function(ids, callBack) {
      return this._start()
          .uri('/api/user/search')
          .urlParameter('ids', ids)
          .get()
          .go(callBack);
  },

  /**
   * Retrieves the users for the given search criteria and pagination.
   *
   * @param {SearchRequest} request The search criteria and pagination constraints. Fields used: queryString, numberOfResults, startRow,
   *    and sort fields.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  searchUsersByQueryString: function(request, callBack) {
      return this._start()
          .uri('/api/user/search')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Send an email using an email template id. You can optionally provide <code>requestData</code> to access key value
   * pairs in the email template.
   *
   * @param {string} emailTemplateId The id for the template.
   * @param {SendRequest} request The send email request that contains all of the information used to send the email.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  sendEmail: function(emailTemplateId, request, callBack) {
      return this._start()
          .uri('/api/email/send')
          .urlSegment(emailTemplateId)
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Sends out an email to a parent that they need to register and create a family or need to log in and add a child to their existing family.
   *
   * @param {FamilyEmailRequest} request The request object that contains the parent email.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  sendFamilyRequestEmail: function(request, callBack) {
      return this._start()
          .uri('/api/user/family/request')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Send a passwordless authentication code in an email to complete login.
   *
   * @param {PasswordlessSendRequest} request The passwordless send request that contains all of the information used to send an email containing a code.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  sendPasswordlessCode: function(request, callBack) {
      return this._start()
          .uri('/api/passwordless/send')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Send a Two Factor authentication code to assist in setting up Two Factor authentication or disabling.
   *
   * @param {TwoFactorSendRequest} request The request object that contains all of the information used to send the code.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  sendTwoFactorCode: function(request, callBack) {
      return this._start()
          .uri('/api/two-factor/send')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Send a Two Factor authentication code to allow the completion of Two Factor authentication.
   *
   * @param {string} twoFactorId The Id returned by the Login API necessary to complete Two Factor authentication.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  sendTwoFactorCodeForLogin: function(twoFactorId, callBack) {
      return this._start()
          .header('Content-Type', 'text/plain')
          .uri('/api/two-factor/send')
          .urlSegment(twoFactorId)
          .post()
          .go(callBack);
  },

  /**
   * Complete login using a 2FA challenge
   *
   * @param {TwoFactorLoginRequest} request The login request that contains the user credentials used to log them in.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  twoFactorLogin: function(request, callBack) {
      return this._start()
          .uri('/api/two-factor/login')
          .setJSONBody(request)
          .post()
          .go(callBack);
  },

  /**
   * Updates the application with the given Id.
   *
   * @param {string} applicationId The Id of the application to update.
   * @param {ApplicationRequest} request The request that contains all of the new application information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateApplication: function(applicationId, request, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the application role with the given id for the application.
   *
   * @param {string} applicationId The Id of the application that the role belongs to.
   * @param {string} roleId The Id of the role to update.
   * @param {ApplicationRequest} request The request that contains all of the new role information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateApplicationRole: function(applicationId, roleId, request, callBack) {
      return this._start()
          .uri('/api/application')
          .urlSegment(applicationId)
          .urlSegment("role")
          .urlSegment(roleId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the consent with the given Id.
   *
   * @param {string} consentId The Id of the consent to update.
   * @param {ConsentRequest} request The request that contains all of the new consent information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateConsent: function(consentId, request, callBack) {
      return this._start()
          .uri('/api/consent')
          .urlSegment(consentId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the email template with the given Id.
   *
   * @param {string} emailTemplateId The Id of the email template to update.
   * @param {EmailTemplateRequest} request The request that contains all of the new email template information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateEmailTemplate: function(emailTemplateId, request, callBack) {
      return this._start()
          .uri('/api/email/template')
          .urlSegment(emailTemplateId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the group with the given Id.
   *
   * @param {string} groupId The Id of the group to update.
   * @param {GroupRequest} request The request that contains all of the new group information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateGroup: function(groupId, request, callBack) {
      return this._start()
          .uri('/api/group')
          .urlSegment(groupId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the identity provider with the given Id.
   *
   * @param {string} identityProviderId The Id of the identity provider to update.
   * @param {IdentityProviderRequest} request The request object that contains the updated identity provider.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateIdentityProvider: function(identityProviderId, request, callBack) {
      return this._start()
          .uri('/api/identity-provider')
          .urlSegment(identityProviderId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the available integrations.
   *
   * @param {IntegrationRequest} request The request that contains all of the new integration information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateIntegrations: function(request, callBack) {
      return this._start()
          .uri('/api/integration')
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the key with the given Id.
   *
   * @param {string} keyId The Id of the key to update.
   * @param {KeyRequest} request The request that contains all of the new key information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateKey: function(keyId, request, callBack) {
      return this._start()
          .uri('/api/key')
          .urlSegment(keyId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the lambda with the given Id.
   *
   * @param {string} lambdaId The Id of the lambda to update.
   * @param {LambdaRequest} request The request that contains all of the new lambda information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateLambda: function(lambdaId, request, callBack) {
      return this._start()
          .uri('/api/lambda')
          .urlSegment(lambdaId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the registration for the user with the given id and the application defined in the request.
   *
   * @param {string} userId The Id of the user whose registration is going to be updated.
   * @param {RegistrationRequest} request The request that contains all of the new registration information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateRegistration: function(userId, request, callBack) {
      return this._start()
          .uri('/api/user/registration')
          .urlSegment(userId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the system configuration.
   *
   * @param {SystemConfigurationRequest} request The request that contains all of the new system configuration information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateSystemConfiguration: function(request, callBack) {
      return this._start()
          .uri('/api/system-configuration')
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the tenant with the given Id.
   *
   * @param {string} tenantId The Id of the tenant to update.
   * @param {TenantRequest} request The request that contains all of the new tenant information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateTenant: function(tenantId, request, callBack) {
      return this._start()
          .uri('/api/tenant')
          .urlSegment(tenantId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the user with the given Id.
   *
   * @param {string} userId The Id of the user to update.
   * @param {UserRequest} request The request that contains all of the new user information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateUser: function(userId, request, callBack) {
      return this._start()
          .uri('/api/user')
          .urlSegment(userId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the user action with the given Id.
   *
   * @param {string} userActionId The Id of the user action to update.
   * @param {UserActionRequest} request The request that contains all of the new user action information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateUserAction: function(userActionId, request, callBack) {
      return this._start()
          .uri('/api/user-action')
          .urlSegment(userActionId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the user action reason with the given Id.
   *
   * @param {string} userActionReasonId The Id of the user action reason to update.
   * @param {UserActionReasonRequest} request The request that contains all of the new user action reason information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateUserActionReason: function(userActionReasonId, request, callBack) {
      return this._start()
          .uri('/api/user-action-reason')
          .urlSegment(userActionReasonId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates a single User consent by Id.
   *
   * @param {string} userConsentId The User Consent Id
   * @param {UserConsentRequest} request The request that contains the user consent information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateUserConsent: function(userConsentId, request, callBack) {
      return this._start()
          .uri('/api/user/consent')
          .urlSegment(userConsentId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Updates the webhook with the given Id.
   *
   * @param {string} webhookId The Id of the webhook to update.
   * @param {WebhookRequest} request The request that contains all of the new webhook information.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  updateWebhook: function(webhookId, request, callBack) {
      return this._start()
          .uri('/api/webhook')
          .urlSegment(webhookId)
          .setJSONBody(request)
          .put()
          .go(callBack);
  },

  /**
   * Validates the provided JWT (encoded JWT string) to ensure the token is valid. A valid access token is properly
   * signed and not expired.
   * <p>
   * This API may be used to verify the JWT as well as decode the encoded JWT into human readable identity claims.
   *
   * @param {string} encodedJWT The encoded JWT (access token).
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  validateJWT: function(encodedJWT, callBack) {
      return this._start()
          .uri('/api/jwt/validate')
          .authorization('JWT ' + encodedJWT)
          .get()
          .go(callBack);
  },

  /**
   * Confirms a email verification. The Id given is usually from an email sent to the user.
   *
   * @param {string} verificationId The email verification id sent to the user.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  verifyEmail: function(verificationId, callBack) {
      return this._start()
          .header('Content-Type', 'text/plain')
          .uri('/api/user/verify-email')
          .urlSegment(verificationId)
          .post()
          .go(callBack);
  },

  /**
   * Confirms an application registration. The Id given is usually from an email sent to the user.
   *
   * @param {string} verificationId The registration verification Id sent to the user.
   * @param {Function} callBack The response handler call back. This function will be passed the ClientResponse object.
   */
  verifyRegistration: function(verificationId, callBack) {
      return this._start()
          .header('Content-Type', 'text/plain')
          .uri('/api/user/verify-registration')
          .urlSegment(verificationId)
          .post()
          .go(callBack);
  },

  /* ===================================================================================================================
   * Private methods
   * ===================================================================================================================*/

  /**
   * creates a rest client
   *
   * @returns {RESTClient} The RESTClient that will be used to call.
   * @private
   */
  _start: function() {
    return new RESTClient().authorization(this.apiKey).setUrl(this.host);
  }
};